<?php

namespace Database\Seeders;

use App\Models\Church;
use App\Models\InventoryItem;
use Illuminate\Database\Seeder;

class InventoryFromPlanilhaSeeder extends Seeder
{
    public function run(): void
    {
        $churchId = Church::where('active', true)->orderBy('name')->value('id');
        if (!$churchId) {
            $this->command->warn('Nenhuma igreja ativa. Crie uma igreja antes de rodar este seeder.');
            return;
        }

        $items = [
            [
                'barcode' => '0A239QBW505407',
                'serial_number' => '0A239QBW505407',
                'name' => 'Notebook Samsung Book Ci5 8GB 256SSD Intel Iris Xe W11 Prateado',
                'category' => 'Eletrônicos',
                'brand' => 'Samsung',
                'item_type' => 'Notebook',
                'classification' => 'Franquia',
                'acquisition_date' => '2025-03-01',
                'acquisition_value' => 329.90,
                'current_value' => 329.90,
                'status' => 'active',
            ],
            [
                'barcode' => 'DHM4KL00M',
                'serial_number' => 'DHM4KL00M',
                'name' => 'MacBook Pro M2 16GB SSD 512GB Tela 14 Cinza',
                'category' => 'Eletrônicos',
                'brand' => 'Apple',
                'item_type' => 'Notebook',
                'classification' => 'Franquia',
                'acquisition_date' => '2025-03-01',
                'acquisition_value' => 16858.94,
                'current_value' => 1695.89,
                'status' => 'active',
            ],
            [
                'barcode' => '1124001749',
                'serial_number' => '1124001749',
                'name' => 'Lente RF24-70 2.8',
                'category' => 'Equipamentos',
                'brand' => 'Canon',
                'item_type' => 'Lente',
                'classification' => 'Básico',
                'acquisition_date' => '2025-03-01',
                'acquisition_value' => 21300.00,
                'current_value' => 745.50,
                'status' => 'active',
            ],
            [
                'barcode' => '302227000626',
                'serial_number' => '302227000626',
                'name' => 'Canon EOS R R5 Mirrorless Preto',
                'category' => 'Eletrônicos',
                'brand' => 'Canon',
                'item_type' => 'Camera',
                'classification' => 'Franquia',
                'acquisition_date' => '2025-03-01',
                'acquisition_value' => 20200.00,
                'current_value' => 2820.00,
                'status' => 'active',
            ],
            [
                'barcode' => '21BRAEEY01061',
                'serial_number' => '21BRAEEY01061',
                'name' => 'Stagebox RIO3224-02',
                'category' => 'Equipamentos',
                'brand' => 'Yamaha',
                'item_type' => 'Stagebox',
                'classification' => 'Básico',
                'acquisition_date' => '2025-03-01',
                'acquisition_value' => 60542.50,
                'current_value' => 1968.05,
                'status' => 'active',
            ],
            [
                'barcode' => '21BRAEEY01059',
                'serial_number' => '21BRAEEY01059',
                'name' => 'Stagebox RIO3224-02',
                'category' => 'Equipamentos',
                'brand' => 'Yamaha',
                'item_type' => 'Stagebox',
                'classification' => 'Básico',
                'acquisition_date' => '2025-03-01',
                'acquisition_value' => 60542.50,
                'current_value' => 1968.05,
                'status' => 'active',
            ],
            [
                'barcode' => '2112130724001016',
                'serial_number' => '2112130724001016',
                'name' => 'Amplificador de Potência Digital 03NXAMP4X4MK2',
                'category' => 'Eletrônicos',
                'brand' => 'Nexo',
                'item_type' => 'Amplifica',
                'classification' => 'Básico',
                'acquisition_date' => '2025-03-01',
                'acquisition_value' => 79964.18,
                'current_value' => 2600.03,
                'status' => 'active',
            ],
            [
                'barcode' => '2130840824A00294',
                'serial_number' => '2130840824A00294',
                'name' => 'Interface Digital Nexo NXAED',
                'category' => 'Equipamentos',
                'brand' => 'Nexo',
                'item_type' => 'Interface',
                'classification' => 'Básico',
                'acquisition_date' => '2025-03-01',
                'acquisition_value' => 4790.74,
                'current_value' => 155.73,
                'status' => 'active',
            ],
            [
                'barcode' => '213385100430',
                'serial_number' => '213385100430',
                'name' => 'Caixa Acústica Passiva 01120',
                'category' => 'Eletrônicos',
                'brand' => 'Nexo',
                'item_type' => 'Caixa de S',
                'classification' => 'Básico',
                'acquisition_date' => '2025-03-01',
                'acquisition_value' => 28210.97,
                'current_value' => 917.05,
                'status' => 'active',
            ],
            [
                'barcode' => '213385100428',
                'serial_number' => '213385100428',
                'name' => 'Caixa Acústica Passiva 01120',
                'category' => 'Eletrônicos',
                'brand' => 'Nexo',
                'item_type' => 'Caixa de S',
                'classification' => 'Básico',
                'acquisition_date' => '2025-03-01',
                'acquisition_value' => 28210.97,
                'current_value' => 917.05,
                'status' => 'active',
            ],
            [
                'barcode' => '213392100436',
                'serial_number' => '213392100436',
                'name' => 'Caixa Acústica Passiva 01P18',
                'category' => 'Eletrônicos',
                'brand' => 'Nexo',
                'item_type' => 'Caixa de S',
                'classification' => 'Básico',
                'acquisition_date' => '2025-03-01',
                'acquisition_value' => 29184.71,
                'current_value' => 948.70,
                'status' => 'active',
            ],
            [
                'barcode' => '213392100421',
                'serial_number' => '213392100421',
                'name' => 'Caixa Acústica Passiva 01P18',
                'category' => 'Eletrônicos',
                'brand' => 'Nexo',
                'item_type' => 'Caixa de S',
                'classification' => 'Básico',
                'acquisition_date' => '2025-03-01',
                'acquisition_value' => 29184.71,
                'current_value' => 948.70,
                'status' => 'active',
            ],
            [
                'barcode' => '26701233AJ',
                'serial_number' => '26701233AJ',
                'name' => 'Comutador de Rede Yamaha SWR2310-10G',
                'category' => 'Eletrônicos',
                'brand' => 'Yamaha',
                'item_type' => 'Switcher',
                'classification' => 'Básico',
                'acquisition_date' => '2025-03-01',
                'acquisition_value' => 4868.36,
                'current_value' => 158.26,
                'status' => 'active',
            ],
            [
                'barcode' => '26701217Al',
                'serial_number' => '26701217Al',
                'name' => 'Comutador de Rede Yamaha SWR2310-10G',
                'category' => 'Eletrônicos',
                'brand' => 'Yamaha',
                'item_type' => 'Switcher',
                'classification' => 'Básico',
                'acquisition_date' => '2025-03-01',
                'acquisition_value' => 4868.36,
                'current_value' => 158.26,
                'status' => 'active',
            ],
            [
                'barcode' => '26701274AJ',
                'serial_number' => '26701274AJ',
                'name' => 'Comutador de Rede Yamaha SWR2310-10G',
                'category' => 'Eletrônicos',
                'brand' => 'Yamaha',
                'item_type' => 'Switcher',
                'classification' => 'Básico',
                'acquisition_date' => '2025-03-01',
                'acquisition_value' => 4868.36,
                'current_value' => 158.26,
                'status' => 'active',
            ],
            [
                'barcode' => '26701213AJ',
                'serial_number' => '26701213AJ',
                'name' => 'Comutador de Rede Yamaha SWR2310-10G',
                'category' => 'Eletrônicos',
                'brand' => 'Yamaha',
                'item_type' => 'Switcher',
                'classification' => 'Básico',
                'acquisition_date' => '2025-03-01',
                'acquisition_value' => 4868.36,
                'current_value' => 158.26,
                'status' => 'active',
            ],
            [
                'barcode' => '21BRAGEZ01015',
                'serial_number' => '21BRAGEZ01015',
                'name' => 'MISTURADOR DE SOM DIGITAL YAMAHA DM7',
                'category' => 'Eletrônicos',
                'brand' => 'Yamaha',
                'item_type' => 'Mesa de S',
                'classification' => 'Básico',
                'acquisition_date' => '2025-03-01',
                'acquisition_value' => 178645.00,
                'current_value' => 5824.32,
                'status' => 'active',
            ],
        ];

        foreach ($items as $data) {
            InventoryItem::firstOrCreate(
                ['barcode' => $data['barcode']],
                array_merge($data, ['church_id' => $churchId])
            );
        }

        $this->command->info('Cadastrados ' . count($items) . ' itens de inventário da planilha.');
    }
}
