/** Permissões por rota do menu lateral (Sidebar só para quem tem `auth.canAccessAdminMenu`). */
export const adminSidebarRoutePermissions: Record<string, string[]> = {
    dashboard: [],
    'prayer.index': ['prayer.manage'],
    'members.index': ['members.view', 'members.manage'],
    'members.show': ['members.view', 'members.manage'],
    'departments.index': ['departments.view', 'departments.manage'],
    'escalas.index': ['escalas.view', 'escalas.manage'],
    'volunteers.index': ['volunteers.view', 'volunteers.manage'],
    'volunteers.show': ['volunteers.view', 'volunteers.manage'],
    'ministry-lead.volunteers.index': ['volunteers.view', 'volunteers.manage', 'volunteers.ministry_operate'],
    'ministry-lead.volunteers.pipeline.stages.store': ['volunteers.ministry_operate', 'volunteers.manage'],
    'ministry-lead.volunteers.pipeline.detail': ['volunteers.ministry_operate', 'volunteers.manage'],
    'ministry-lead.volunteers.pipeline.notes.store': ['volunteers.ministry_operate', 'volunteers.manage'],
    'ministry-lead.volunteers.pipeline.stage': ['volunteers.ministry_operate', 'volunteers.manage'],
    'ministry-lead.volunteers.board': ['volunteers.ministry_operate', 'volunteers.manage'],
    'ministry-lead.volunteers.show': ['volunteers.ministry_operate', 'volunteers.manage'],
    'ministry-lead.volunteers.assistant': ['volunteers.ministry_operate', 'volunteers.manage'],
    'rooms.index': ['rooms.view', 'rooms.manage'],
    'room-bookings.index': ['rooms.view', 'rooms.manage', 'rooms.schedule'],
    'inventory.index': ['inventory.view', 'inventory.manage'],
    'roles.index': ['roles.manage'],
    'news.index': ['news.view', 'news.manage'],
    /** No Sidebar o item só entra no bloco ADM com `auth.isSuperAdmin`; rota `role:super_admin`. */
    'operations.index': [],
    /** No Sidebar o item só entra no bloco ADM com `auth.isSuperAdmin`; rotas são `role:super_admin`. */
    'churches.index': ['churches.manage'],
    'churches.services.index': ['churches.manage'],
    'events.index': ['events.view', 'events.manage'],
    'culto.index': ['culto.manage'],
    'musica.index': ['music.manage'],
    'photo-albums.index': ['photos.manage'],
    'services.index': [],
    /** Visibilidade real: só `super_admin` via auth.canManageSettings no Sidebar (bloco ADM). */
    'settings.index': [],
    'support.index': ['support.view', 'support.manage'],
    'solicitations.index': ['solicitations.view', 'solicitations.manage'],
    'pastors.index': ['pastors.view', 'pastors.manage'],
    /** Visibilidade no Sidebar: `auth.pastoralAgendaMenuVisible` (pastor ligado, admin, gestão de pastores, etc.). */
    'pastoral-agenda.index': [],
    'app-versions.index': ['notifications.manage'],
    'notifications.manage': ['notifications.manage'],
    'more.index': [],
    'varios.schedule': [],
    'varios.services': [],
    'varios.classe-comecos': [],
    'varios.acervo': [],
    /** Mesma permissão de gestão de músicas / inserir itens no acervo */
    'acervo.index': ['music.manage'],
    'varios.contact': [],
    'varios.notifications': [],
};
