/** Permissões por rota do menu lateral (Sidebar em AdminLayout e MobileLayout logado). */
export const adminSidebarRoutePermissions: Record<string, string[]> = {
    dashboard: [],
    'members.index': ['members.view', 'members.manage'],
    'departments.index': ['departments.view', 'departments.manage'],
    'escalas.index': ['escalas.view', 'escalas.manage'],
    'volunteers.index': ['volunteers.view', 'volunteers.manage'],
    'rooms.index': ['rooms.view', 'rooms.manage'],
    'inventory.index': ['inventory.view', 'inventory.manage'],
    'users.index': ['users.view', 'users.manage'],
    'roles.index': ['roles.manage'],
    'news.index': ['news.view', 'news.manage'],
    'churches.index': ['churches.manage'],
    'churches.services.index': ['churches.manage'],
    'events.index': ['events.view', 'events.manage'],
    'culto.index': ['culto.manage'],
    'musica.index': ['music.manage'],
    'services.index': [],
    'settings.index': [],
    'more.index': [],
    'varios.schedule': [],
    'varios.services': [],
    'varios.classe-comecos': [],
    'varios.acervo': [],
    'acervo.index': [],
    'varios.contact': [],
    'varios.notifications': [],
    'prayer.index': [],
    'mobile.prayer': [],
};
